statr creating .github workflow to deploy

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -1,6 +1,9 @@
 name: Deploy App
 
 on:
+  push:
+    branches:
+      - main
   workflow_dispatch:
     inputs:
       tag:
@@ -10,8 +13,25 @@ on:
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    env:
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          ref: ${{github.event.inputs.tag}}
+      - name: Check if tag exists
+        run: |
+            git fetch --all --tags
+            if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
+              echo "error: Tag '${{ github.event.inputs.tag }}' not found"
+              exit 1
+            fi
+      - name: Set up golang
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.23.1
+      - name: Build app
+        run: |
+            go mod download
+            go build -o ./.bin/main ./cmd/main/main.go
 
 
